config/routes.rb
Rails.application.routes.draw do
  resources :notices
  resources :subscriptions, only: [:create, :update, :destroy, :index]

  resources :addstudents
  resources :galleries
  resources :events
  resources :divisions
  resources :subjects
  resources :teachers
  resources :master_timetables
  get 'maker/index'
  devise_for :admins, controller:{
    sessions: 'admins/sessions'
  }

  get 'events_data', to: 'maker#events_data'
  get 'notices_data', to: 'maker#notices_data'

  get '/index', to: 'addstudents#index', as: 'search_addstudents'

  get '/webmanifest/manifest.json', to: 'application#manifest'

# subscriptions
  post '/subscribe', to: 'pages#sub_create'

  get '/index', to: 'pages#index', as: 'pages_index'
  get '/about_us', to: 'pages#about_us', as: 'pages_about_us'
  get '/about', to: 'pages#about', as: 'pages_about'
  get '/contact', to: 'pages#contact', as: 'pages_contact'
  get 'master_timetables/render_master_timetable_pdf', to: 'master_timetables#render_master_timetable_pdf', as: 'render_master_timetable_pdf'
  get 'addstudents/download_pdf', to: 'addstudents#download_pdf', as: 'download_pdf_students'

    get '/pages/userEvents', to: 'pages#userEvents', as: 'pages_userEvents'
  get '/map', to: 'pages#map', as: 'pages_map'
  get '/time_table_list', to: 'pages#time_table_list', as: 'pages_time_table_list'
  get '/weekly_timetable', to: 'pages#weekly_timetable', as: 'weekly_timetable'
  


  get 'notices/filter_by_category', to: 'pages#notices_summary', as: 'filter_notices_by_category'

  get '/notices_summary', to: 'pages#notices_summary', as: 'notices_summary'
  get '/notices_details/:id', to: 'pages#notices_details', as: 'notices_details'
  

  get '/events_summary', to: 'pages#events_summary', as: 'events_summary'
  get '/events_details/:id', to: 'pages#events_details', as: 'events_details'
  
  get '/galleries_summary', to: 'pages#gallery_summary', as: 'galleries_summary'
  get '/galleries_details/:id', to: 'pages#gallery_details', as: 'galleries_details'

  get '/teachers_summary', to: 'pages#teachers_summary', as: 'teachers_summary'
  get '/teachers_details/:id', to: 'pages#teachers_details', as: 'teachers_details'
  
  # Route for selecting the division
  get '/select_division', to: 'maker#select_division', as: 'select_division'
  
  # Route for displaying the timetable based on the selected division
  get '/display_timetable', to: 'maker#display_timetable', as: 'display_timetable'
  get '/whyOurSch', to: 'pages#whyOurSch', as: 'whyOurSch'

  get '/our_trust', to: 'pages#our_Trusties', as: 'our_Trust'

  get '/news', to: 'pages#googleNews', as: 'news'
  
  # Route for updating the master timetable
  post 'update_master_timetable', to: 'maker#update_master_timetable', as: 'update_master_timetable'

  post '/week_timetable/:division_id', to: 'maker#week_timetable', as: 'week_timetable'

  resources :master_timetables do
    post 'upload', on: :collection
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount ActionCable.server => '/cable'

  # Defines the root path route ("/")
  root "pages#index"
end

app/controllers/maker_controller.rb
class MakerController < ApplicationController
  before_action :authenticate_admin!

  def index
    @addstudents = Addstudent.all
    @divisions = Division.all
    @master_timetables = MasterTimetable.all
    @galleries = Gallery.all
    @notices = Notice.where(deleted_at: nil)
    @subjects = Subject.all
    @teachers = Teacher.all
    @events = Event.all
    @events_data = Event.group("DATE_TRUNC('month', created_at)").count
    @notices_data = Notice.group("DATE_TRUNC('month', created_at)").count

    respond_to do |format|
      format.html
      format.json { render json: { events_data: @events_data, notices_data: @notices_data } }
    end
  end


  def select_division
    @divisions = Division.all
  end

  def display_timetable
    @division = Division.find(params[:division_id])
    @master_timetable = MasterTimetable.where(division_id: @division.id)
    @subjects = Subject.all
    @teachers = Teacher.all
  end
  

  def update_master_timetable
    master_timetable_params[:master_timetable].each do |entry|
      master_timetable = MasterTimetable.find_by(id: entry[:id].to_i)
      if master_timetable
        master_timetable.update(entry.except(:id))
      end
    end
  
    redirect_to display_timetable_path(division_id: params[:division_id])
  end
  
  

  private


      def master_timetable_params
        params.permit(master_timetable: [:id, :day_id, :time_slot_id, :subject_id, :teacher_id])
      end


  
  def your_method_name_here(entry_params)
    entry_params[:timetable_entries].each do |entry|
      subject_id = entry[:subject_id].to_i
      teacher_id = entry[:teacher_id].to_i

    end
  end
  
  
end

app/helpers/maker_helper.rb
module MakerHelper
end

app/views/maker/_admin_nav.html.erb
<html class="dark scroll-smooth">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="/dist/output.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>

<body class="h-screen">

    <header class="h-14 bg-gray-100 top-0 w-full fixed shadow" style="z-index: 99999;">
        <div class="flex justify-between items-center px-10 h-14">
            <div class="flex justify-between items-center gap-x-14">
                <div class="w-40">
                    <h2 class="text-md font-bold" href="#">Admin</h2>
                    <p class="text-gray-400 text-[12px]">
                         Website Administrator
                    </p>
                </div>



            </div>
        </div>
    </header>

    <!-- main content -->
    <main class="h-[calc(100vh-120px)] w-full absolute top-14">
        <!-- left sidebar -->
        <aside id="sidebar"
            class="w-[60px] lg:w-[240px] h-[calc(100vh-120px)] whitespace-nowrap fixed shadow overflow-x-hidden transition-all duration-500 ease-in-out">
            <div class="flex flex-col justify-between h-full">
                <ul class="flex flex-col gap-1 mt-2">

                    <li class="text-gray-500 hover:bg-gray-100 hover:text-gray-900">
     <%= link_to(addstudents_path, class: "w-full flex items-center py-3") do %>
                       <i class="fas fa-user text-center px-6"></i>
                            <span class="whitespace-nowrap pl-1">Add Students</span>
                               <% end %>
                        </a>
                    </li>

                    <li class="text-gray-500 hover:bg-gray-100 hover:text-gray-900">
       <%= link_to(teachers_path, class: "w-full flex items-center py-3") do %>
                            <i class="fas fa-users text-center px-5"></i>
                            <span class="whitespace-nowrap pl-1">Add Teachers</span>
                            <% end %>
                    </li>

                    <li class="text-gray-500 hover:bg-gray-100 hover:text-gray-900">
         <%= link_to(subjects_path, class: "w-full flex items-center py-3") do %>
                            <i class="fas fa-book text-center px-6"></i>
                            <span class="whitespace-nowrap pl-1">Add Subject</span>
                               <% end %>
                    </li>

                    <li class="text-gray-500 hover:bg-gray-100 hover:text-gray-900">
    <%= link_to(notices_path, class: "w-full flex items-center py-3") do %>
                           <i class="fa-regular fa-note-sticky text-center px-6"></i>
                            <span class="whitespace-nowrap pl-1">Add Notices</span>
                               <% end %>
                    </li>

                    <li class="text-gray-500 hover:bg-gray-100 hover:text-gray-900">
    <%= link_to(events_path, class: "w-full flex items-center py-3") do %>
                          <i class="fa-regular fa-calendar text-center px-6"></i>
                            <span class="whitespace-nowrap pl-1">Add Events</span>
                               <% end %>
                    </li>

                    <li class="text-gray-500 hover:bg-gray-100 hover:text-gray-900">
       <%= link_to(galleries_path, class: "w-full flex items-center py-3") do %>
                           <i class="fa-regular fa-image text-center px-6"></i>
                            <span class="whitespace-nowrap pl-1">Add Images</span>
   <% end %>
                    </li>

                    <li class="text-gray-500 hover:bg-gray-100 hover:text-gray-900">
    <%= link_to(divisions_path, class: "w-full flex items-center py-3") do %>
                          <i class="fa-solid fa-chalkboard-user text-center px-6"></i>
                            <span class="whitespace-nowrap pl-1">Add Classes</span>
   <% end %>
                    </li>

                    <li class="text-gray-500 hover:bg-gray-100 hover:text-gray-900">
    <%= link_to(master_timetables_path, class: "w-full flex items-center py-3") do %>
                          <i class="fas fa-table list text-center px-6"></i>
                            <span class="whitespace-nowrap pl-1">Edit Master Time-Table</span>
   <% end %>
                    </li>

                    <li class="text-gray-500 hover:bg-gray-100 hover:text-gray-900">
    <%= link_to(select_division_path, class: "w-full flex items-center py-3") do %>
                          <i class="fas fa-table list text-center px-6"></i>
                            <span class="whitespace-nowrap pl-1">Edit Week Time-Table</span>
   <% end %>
                    </li>
                
                </ul>

<%= form_tag destroy_admin_session_path, method: :delete, class: "flex flex-col gap-1 mt-2" do %>
  <%= submit_tag "Logout", class: "w-full flex items-center justify-center py-3  text-black " do %>
    Logout
  <% end %>
<% end %>

            </div>
        </aside>

        <!-- main content -->
        <section id="content"
            class="w-[100wh-60px] lg:w-[100wh-250px] ml-[60px] lg:ml-[240px] p-5 right-0 transition-all duration-500 ease-in-out">
            <!-- user summary -->
            <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">
                <div class="bg-slate-50 p-5 m-2 rounded-md flex justify-between items-center shadow">
                    <div>
                        <h3 class="font-bold">Total Students</h3>
                        <p class="text-gray-500"><%= Addstudent.count %></p>

                    </div>
                    <i class="fa-solid fa-users p-4 bg-gray-200 rounded-md"></i>
                </div>

                <div class="bg-slate-50 p-5 m-2 flex justify-between items-center shadow">
                    <div>
                        <h3 class="font-bold">Total Teachers</h3>
                        <p class="text-gray-500"><%= Teacher.count%></p>
                    </div>
                    <i class="fa-solid fa-users p-4 bg-green-200 rounded-md"></i>
                </div>

                <div class="bg-slate-50 p-5 m-2 flex justify-between items-center shadow">
                    <div>
                        <h3 class="font-bold">Total Notices</h3>
                        <p class="text-gray-500"><%= Notice.count%></p>
                    </div>
                    <i class="fa-solid fa-users p-4 bg-yellow-200 rounded-md"></i>
                </div>

                <div class="bg-slate-50 p-5 m-2 flex justify-between items-center shadow">
                    <div>
                        <h3 class="font-bold">Total Events</h3>
                        <p class="text-gray-500"><%= Event.count%></p>
                    </div>
                    <i class="fa-solid fa-users p-4 bg-red-200 rounded-md"></i>
                </div>
            </div>


            <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
<canvas id="myChart" width="400" height="400"></canvas>
    <canvas id="myChart2" width="400" height="400"></canvas>

    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const canvas = document.getElementById('myChart');
            let myChart;

            // Fetch data for events
            fetch('/events_data')
                .then(response => response.json())
                .then(eventsData => {
                    const config = {
                        type: 'line',
                        data: {
                            labels: Object.keys(eventsData),
                            datasets: [{
                                label: 'Events Organized per Month',
                                data: Object.values(eventsData),
                                backgroundColor: 'rgba(54, 162, 235, 0.5)', // Change the color as needed
                                borderColor: 'rgb(54, 162, 235)',
                                borderWidth: 1,
                                fill: true,
                                tension: 0.4,
                            }]
                        },
                        options: {
                            plugins: {
                                title: {
                                    display: true,
                                    text: 'Events Organized per Month'
                                }
                            },
                            scales: {
                                y: {
                                    stacked: true,
                                    beginAtZero: true
                                },
                                x: {
                                    stacked: true
                                }
                            }
                        }
                    };

                    myChart = new Chart(canvas, config);
                });
        });
    </script>

</body>

</html>

app/views/maker/display_timetable.html.erb
<% # Group entries by day %>
<% @master_timetable.group_by(&:day_id).each do |day_id, entries| %>
  <div class="mt-4">
    <h3 class="text-lg font-semibold mb-2"><%= entries.first.day.name %></h3>
    <%= form_tag(update_master_timetable_path, method: :post, class: "bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4", id: "form_#{day_id}") do %>
      <table class="w-full">
        <thead>
          <tr>
            <th class="px-4 py-2">Time Slot</th>
            <th class="px-4 py-2">Subject</th>
            <th class="px-4 py-2">Teacher</th>
          </tr>
        </thead>
        <tbody>
          <% # Sort entries by time_slot start_time before iterating %>
          <% entries.sort_by { |entry| entry.time_slot.start_time }.each do |entry| %>
            <tr>
              <% start_time, end_time = entry.time_slot.start_time.strftime('%I:%M %p'), entry.time_slot.end_time.strftime('%I:%M %p') %>
              <td class="border px-4 py-2"><%= start_time %> - <%= end_time %></td>
              <td class="border px-4 py-2">
                <%= hidden_field_tag "master_timetable[][id]", entry.id %>
                <%= hidden_field_tag "master_timetable[][day_id]", entry.day_id %>
                <%= hidden_field_tag "master_timetable[][time_slot_id]", entry.time_slot_id %>
                <%= select_tag "master_timetable[][subject_id]", options_for_select(@subjects.map { |subject| [subject.name, subject.id] }, entry.subject_id), class: "w-full" %>
              </td>
              <td class="border px-4 py-2">
                <%= select_tag "master_timetable[][teacher_id]", options_for_select(@teachers.map { |teacher| [teacher.name, teacher.id] }, entry.teacher_id), class: "w-full" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <%= button_tag "Update Master Timetable", type: "submit", class: "bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 mt-2 rounded focus:outline-none focus:shadow-outline", data: { confirm: "Are you sure you want to update the timetable for #{entries.first.day.name}?" } %>
    <% end %>
  </div>
<% end %>

app/views/maker/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <%= render "admin_nav"%>
</body>
</html>

app/views/maker/select_division.html.erb
<div class="h-screen">
  <div class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4 max-w-xs mt-10 mx-auto">
    <h1 class="text-2xl font-bold mb-4">Select Division</h1>
    <%= form_tag(display_timetable_path, method: :get) do %>
      <div class="mb-4">
        <%= label_tag :division_id, "Select Division", class: "block text-gray-700 text-sm font-bold mb-2" %>
        <%= select_tag :division_id, options_for_select(@divisions.map { |division| [division.division, division.id] }), include_blank: true, class: "form-select w-full py-2 px-3 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500" %>
      </div>
      <%= submit_tag "Submit", class: "bg-indigo-500 hover:bg-indigo-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" %>
    <% end %>
  </div>
</div>