config/routes.rb
Rails.application.routes.draw do
  resources :notices
  resources :subscriptions, only: [:create, :update, :destroy, :index]

  resources :addstudents
  resources :galleries
  resources :events
  resources :divisions
  resources :subjects
  resources :teachers
  resources :master_timetables
  get 'maker/index'
  devise_for :admins, controller:{
    sessions: 'admins/sessions'
  }

  get 'events_data', to: 'maker#events_data'
  get 'notices_data', to: 'maker#notices_data'

  get '/index', to: 'addstudents#index', as: 'search_addstudents'

  get '/webmanifest/manifest.json', to: 'application#manifest'

# subscriptions
  post '/subscribe', to: 'pages#sub_create'

  get '/index', to: 'pages#index', as: 'pages_index'
  get '/about_us', to: 'pages#about_us', as: 'pages_about_us'
  get '/about', to: 'pages#about', as: 'pages_about'
  get '/contact', to: 'pages#contact', as: 'pages_contact'
  get 'master_timetables/render_master_timetable_pdf', to: 'master_timetables#render_master_timetable_pdf', as: 'render_master_timetable_pdf'
  get 'addstudents/download_pdf', to: 'addstudents#download_pdf', as: 'download_pdf_students'

    get '/pages/userEvents', to: 'pages#userEvents', as: 'pages_userEvents'
  get '/map', to: 'pages#map', as: 'pages_map'
  get '/time_table_list', to: 'pages#time_table_list', as: 'pages_time_table_list'
  get '/weekly_timetable', to: 'pages#weekly_timetable', as: 'weekly_timetable'
  


  get 'notices/filter_by_category', to: 'pages#notices_summary', as: 'filter_notices_by_category'

  get '/notices_summary', to: 'pages#notices_summary', as: 'notices_summary'
  get '/notices_details/:id', to: 'pages#notices_details', as: 'notices_details'
  

  get '/events_summary', to: 'pages#events_summary', as: 'events_summary'
  get '/events_details/:id', to: 'pages#events_details', as: 'events_details'
  
  get '/galleries_summary', to: 'pages#gallery_summary', as: 'galleries_summary'
  get '/galleries_details/:id', to: 'pages#gallery_details', as: 'galleries_details'

  get '/teachers_summary', to: 'pages#teachers_summary', as: 'teachers_summary'
  get '/teachers_details/:id', to: 'pages#teachers_details', as: 'teachers_details'
  
  # Route for selecting the division
  get '/select_division', to: 'maker#select_division', as: 'select_division'
  
  # Route for displaying the timetable based on the selected division
  get '/display_timetable', to: 'maker#display_timetable', as: 'display_timetable'
  get '/whyOurSch', to: 'pages#whyOurSch', as: 'whyOurSch'

  get '/our_trust', to: 'pages#our_Trusties', as: 'our_Trust'

  get '/news', to: 'pages#googleNews', as: 'news'
  
  # Route for updating the master timetable
  post 'update_master_timetable', to: 'maker#update_master_timetable', as: 'update_master_timetable'

  post '/week_timetable/:division_id', to: 'maker#week_timetable', as: 'week_timetable'

  resources :master_timetables do
    post 'upload', on: :collection
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  mount ActionCable.server => '/cable'

  # Defines the root path route ("/")
  root "pages#index"
end

app/models/addstudent.rb
class Addstudent < ApplicationRecord
    has_one_attached :photograph
    validate :validate_photograph_format
    validate :validate_marital_status_selection
    validate :validate_Gender_selection
    validate :validate_phone_number_length
    validate :validate_parents_phone_number_length
    private
  
    def validate_photograph_format
      return unless photograph.attached?
  
      unless photograph.image?
        errors.add(:photograph, "must be an image file")
      end
    end
    validates :enrollment_number, presence: true, uniqueness: true
    validates :first_name, presence: true
    validates :middle_name, presence: true
    validates :surname, presence: true
    validates :date_of_birth, presence: true
    validates :phone_number, presence: true, numericality: { only_integer: true }
    validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP, message: "must be a valid email address" }
    validates :address, presence: true
    validates :fathers_name, presence: true
    validates :mothers_name, presence: true
    validates :parents_phone_number, presence: true, numericality: { only_integer: true }
    validates :job_placement, presence: true

    def validate_marital_status_selection
      if marital_status == "Select_Status"
        errors.add(:marital_status, "must be selected")
      end
    end
    def validate_Gender_selection
      if gender == "Select_Gender"
        errors.add(:gender, "must be selected")
      end
    end

    def validate_phone_number_length
      if phone_number.to_s.length != 10
        errors.add(:phone_number, "must be exactly 10 digits")
      end
    end
 
    def validate_parents_phone_number_length
      if parents_phone_number.to_s.length != 10
        errors.add(:parents_phone_number, "must be exactly 10 digits")
      end
    end

end
  

app/controllers/addstudents_controller.rb
class AddstudentsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_addstudent, only: %i[ show edit update destroy ]
  before_action :set_addstudent, except: [:download_pdf]

  # GET /addstudents or /addstudents.json
  def index
    @addstudents = Addstudent.all
    @addstudents = if params[:query].present?
      Addstudent.where('first_name LIKE ?', "%#{params[:query]}%")
    else
      Addstudent.all
    end
  end
  

  # GET /addstudents/1 or /addstudents/1.json
  def show
    if params[:id] == "download_pdf"
      download_pdf
    else
      @addstudent = Addstudent.find(params[:id])
    end
  end

  # GET /addstudents/new
  def new
    @addstudent = Addstudent.new
  end

  # GET /addstudents/1/edit
  def edit
    @addstudent = Addstudent.find(params[:id])
  end

  # POST /addstudents or /addstudents.json
  def create
    @addstudent = Addstudent.new(addstudent_params)

    respond_to do |format|
      if @addstudent.save
        format.html { redirect_to addstudent_url(@addstudent), notice: "Addstudent was successfully created." }
        format.json { render :show, status: :created, location: @addstudent }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @addstudent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addstudents/1 or /addstudents/1.json
  def update
    respond_to do |format|
      if @addstudent.update(addstudent_params)
        format.html { redirect_to addstudents_url, notice: "Addstudent was successfully updated." }
        format.json { render :show, status: :ok, location: @addstudent }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @addstudent.errors, status: :unprocessable_entity }
      end
    end
  end
  
 

  def destroy
    @addstudent = Addstudent.find(params[:id])
    @addstudent.destroy
  
    respond_to do |format|
      format.html { redirect_to addstudents_url, notice: "Addstudent was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  

  def download_pdf
    @students = Addstudent.all 
  
    respond_to do |format|
      format.pdf do
        pdf = Prawn::Document.new
        # Add student data to the PDF document
        table_data = [["Er.No", "Name", "Date of Birth", "Phone Number", "Email", "Address"]]
        @students.each do |addstudent|
          table_data << [  addstudent.enrollment_number,
                          "#{addstudent.first_name} #{addstudent.middle_name} #{addstudent.surname}",
                          addstudent.date_of_birth,
                          addstudent.phone_number,
                          addstudent.email,
                          addstudent.address ]
        end
  
        # Draw the table
        pdf.table(table_data, header: true, width: pdf.bounds.width) do
          row(0).font_style = :bold
          columns(0..5).align = :center
          self.row_colors = ["DDDDDD", "FFFFFF"]
          self.header = true
        end
        send_data pdf.render, filename: "students_data.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  private


  def set_addstudent
    return unless params[:id] != "download_pdf"
    @addstudent = Addstudent.all
  end

    # Only allow a list of trusted parameters through.
    def addstudent_params
      params.require(:addstudent).permit(:photograph, :first_name, :middle_name, :surname, :date_of_birth, :gender, :phone_number, :email, :address, :fathers_name, :mothers_name, :parents_phone_number, :job_placement, :marital_status, :enrollment_number)
    end
end

app/helpers/addstudents_helper.rb
module AddstudentsHelper
end

app/views/addstudents/_addstudent.html.erb
<div id="<%= dom_id addstudent %>" class="mx-auto md:w-2/3 w-full">
  <div class="bg-white border border-gray-300 rounded-md shadow-lg overflow-hidden flex">
    <% if addstudent.photograph.attached? %>
      <div class="flex-shrink-0 p-6 flex justify-center items-center">
        <%= image_tag(addstudent.photograph, class: "rounded-full h-32 w-32 object-cover") %>
      </div>
    <% end %>

    <div class="p-6 flex-grow">
      <div class="px-6 py-4 bg-gray-100 border-b border-gray-300">
        <h2 class="text-xl font-semibold text-gray-800">Student Details</h2>
      </div>

      <table class="w-full">
        <tr>
          <th class="py-2 px-4 text-left font-semibold border-b border-gray-300">Enrollment Number</th>
          <td class="py-2 px-4 text-left border-b border-gray-300"><%= addstudent.enrollment_number %></td>
        </tr>
        <tr>
          <th class="py-2 px-4 text-left font-semibold border-b border-gray-300">Name</th>
          <td class="py-2 px-4 text-left border-b border-gray-300"><%= addstudent.first_name %> <%= addstudent.middle_name %> <%= addstudent.surname %></td>
        </tr>
        <tr>
          <th class="py-2 px-4 text-left font-semibold border-b border-gray-300">Date of Birth</th>
          <td class="py-2 px-4 text-left border-b border-gray-300"><%= addstudent.date_of_birth %></td>
        </tr>
        <tr>
          <th class="py-2 px-4 text-left font-semibold border-b border-gray-300">Gender</th>
          <td class="py-2 px-4 text-left border-b border-gray-300"><%= addstudent.gender %></td>
        </tr>
        <tr>
          <th class="py-2 px-4 text-left font-semibold border-b border-gray-300">Phone Number</th>
          <td class="py-2 px-4 text-left border-b border-gray-300"><%= addstudent.phone_number %></td>
        </tr>
      </table>

      <% if action_name != "show" %>
        <div class="flex justify-center mt-6 gap-2">
          <%= link_to "Show this Student", addstudent, class: "px-4 py-2 bg-gray-200 text-gray-800 font-semibold rounded hover:bg-gray-300 transition duration-300" %>
          <%= link_to "Edit", edit_addstudent_path(addstudent), class: "px-4 py-2 bg-gray-200 text-gray-800 font-semibold rounded hover:bg-gray-300 transition duration-300" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/addstudents/_form.html.erb
<%= form_with(model: addstudent, class: "contents") do |form| %>

  <div class="my-5">
    <div id="image-preview" class="mt-2"></div>
    <%= form.label :photograph, class: "block font-medium mb-1" %>
    <%= form.file_field :photograph, accept: "image/*", onchange: "previewImage(this);", class: "block outline-none" %>
    <% if addstudent.errors.has_key?(:photograph) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:photograph).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:first_name) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:first_name).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :enrollment_number %>
    <%= form.number_field :enrollment_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:enrollment_number) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:enrollment_number).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:middle_name) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:middle_name).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :surname %>
    <%= form.text_field :surname, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:surname) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:surname).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:date_of_birth) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:date_of_birth).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :gender %>
    <%= form.select :gender, ['Select_Gender','Female', 'Male'], {}, class: "block w-full mt-2 p-3 border border-gray-300 rounded-md shadow-sm outline-none focus:ring focus:ring-blue-200 focus:border-blue-500 transition duration-300" %>
    <% if addstudent.errors.has_key?(:gender) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:gender).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :phone_number %>
    <%= form.number_field :phone_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "+91 XXXXXXXXXX" %>
    <% if addstudent.errors.has_key?(:phone_number) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:phone_number).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :email %>
    <%= form.text_field :email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:email) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:email).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :address %>
    <%= form.text_field :address, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:address) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:address).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :fathers_name %>
    <%= form.text_field :fathers_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:fathers_name) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:fathers_name).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :mothers_name %>
    <%= form.text_field :mothers_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:mothers_name) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:mothers_name).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :parents_phone_number %>
    <%= form.number_field :parents_phone_number, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full", placeholder: "+91 XXXXXXXXXX" %>
    <% if addstudent.errors.has_key?(:parents_phone_number) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:parents_phone_number).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :job_placement %>
    <%= form.text_field :job_placement, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
    <% if addstudent.errors.has_key?(:job_placement) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:job_placement).first %>
      </div>
    <% end %>
  </div>

  <div class="my-5">
    <%= form.label :marital_status %>
    <%= form.select :marital_status, ['Select_Status','Married', 'Not-Married'], {}, class: "block w-full mt-2 p-3 border border-gray-300 rounded-md shadow-sm outline-none focus:ring focus:ring-blue-200 focus:border-blue-500 transition duration-300" %>
    <% if addstudent.errors.has_key?(:marital_status) %>
      <div class="text-red-500 mt-1">
        <%= addstudent.errors.full_messages_for(:marital_status).first %>
      </div>
    <% end %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

<script>
  function previewImage(input) {
    var preview = document.getElementById('image-preview');
    preview.innerHTML = '';

    if (input.files && input.files[0]) {
      var reader = new FileReader();

      reader.onload = function (e) {
        var img = document.createElement('img');
        img.src = e.target.result;
        img.classList.add('rounded-full', 'h-20', 'w-20', 'object-cover');
        preview.appendChild(img);
      };

      reader.readAsDataURL(input.files[0]);
    }
  }
</script>

app/views/addstudents/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing addstudent</h1>

  <%= render "form", addstudent: @addstudent %>

  <%= link_to "Show this addstudent", @addstudent, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to addstudents", addstudents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/addstudents/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center p-4">
    <div>
      <nav aria-label="breadcrumb">
        <ul class="flex flex-wrap space-x-3 text-sm font-medium">
          <li class="flex items-center space-x-3">
            <a href="#" class="flex items-center space-x-1 text-gray-800">
              <svg class="h-4 w-4 shrink-0 fill-gray-500" aria-hidden="true" viewBox="0 0 256 256">
                <path d="M184 32H72A16 16 0 0056 48V224a8.1 8.1.0 004.1 7 7.6 7.6.0 003.9 1 7.9 7.9.0 004.2-1.2L128 193.4l59.7 37.4a8.3 8.3.0 008.2.2 8.1 8.1.0 004.1-7V48A16 16 0 00184 32z"></path>
              </svg>
              <%= link_to "Dashboard", maker_index_path %>
            </a>
          </li>
          <li class="flex items-center space-x-3">
            <div aria-hidden="true" class="h-4 w-px rotate-12 rounded-full bg-gray-300"></div>
            <a href="#" class="flex items-center space-x-1 text-gray-800">
              <svg class="h-4 w-4 shrink-0 fill-gray-500" aria-hidden="true" viewBox="0 0 256 256">
                <path d="M2e2 32H163.7a47.8 47.8.0 00-71.4.0H56A16 16 0 0040 48V216a16 16 0 0016 16H2e2a16 16 0 0016-16V48A16 16 0 002e2 32zm-72 0a32.1 32.1.0 0132 32H96a32.1 32.1.0 0132-32z"></path>
              </svg>
              <span>Addstudents</span>
            </a>
          </li>
        </ul>
      </nav>
    </div>
    <div class="flex">
      <%= link_to "New Student", new_addstudent_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium mr-4" %>
      <%= link_to "Download PDF", download_pdf_students_path(format: :pdf), class: "rounded-lg py-3 px-5 bg-green-500 text-white block font-medium" %>
    </div>
  </div>

  <div class="flex items-center justify-between px-4 py-2">
    <%= form_tag(search_addstudents_path, method: :get) do %>
      <%= text_field_tag :query, params[:query], placeholder: "Enter student name...", class: "rounded-lg px-3 py-2 border border-gray-300 focus:outline-none focus:ring-2 focus:ring-blue-600 focus:border-transparent" %>
      <%= submit_tag "Search", class: "rounded-lg py-2 px-4 bg-blue-600 text-white font-medium hover:bg-blue-700 focus:outline-none focus:bg-blue-700" %>
    <% end %>
  </div>

  <div id="addstudents" class="min-w-full mt-8">
    <%= render @addstudents %>
  </div>
</div>

app/views/addstudents/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New addstudent</h1>

  <%= render "form", addstudent: @addstudent %>

  <%= link_to "Back to addstudents", addstudents_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/addstudents/show.html.erb
<div class="mx-auto md:w-2/3 w-full m-12">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-100 text-green-800 mb-5 font-medium rounded-lg text-center" id="notice"><%= notice %></p>
  <% end %>

  <div class="bg-white rounded-lg shadow-md p-6">
    <%= render @addstudent %>

    <div class="mt-4">
      <div class="flex items-center justify-center gap-2">
        <%= link_to "Edit", edit_addstudent_path(@addstudent), class: "rounded-lg py-2 px-4 bg-gray-200 text-gray-800 font-medium hover:bg-gray-300 transition duration-300" %>
        
        <%= button_to "Destroy", addstudent_path(@addstudent), method: :delete, data: { confirm: 'Are you sure?' }, class: "rounded-lg py-2 px-4 bg-red-200 text-red-800 font-medium hover:bg-red-300 transition duration-300" %>
        
        <%= link_to "Back to Addstudents", addstudents_path, class: "rounded-lg py-2 px-4 bg-gray-200 text-gray-800 font-medium hover:bg-gray-300 transition duration-300" %>
      </div>
    </div>
  </div>
</div>